name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Maven
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mvn -B clean package -DbaseVersion=${{ github.event.release.tag_name }}
          mkdir staging && cp target/*.jar staging
        if: !startsWith(github.ref, 'refs/tags/')
        run: |
          mvn -B clean package
          mkdir staging && cp target/*.jar staging

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging

      - name: Make Release
        uses: softprops/action-gh-release@v0.1.5
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files:
            target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
